### ISSUE TITLE
请问cli方式调用 to_wav为什么报错

### ISSUE THREAD

**Issue by lanyuer** [fishaudio/audio-preprocess#11]
python -m cli to_wav -h
----> Error: No such command 'to_wav'.

python -m cli length -h
没问题

没看出来是什么导致的不同

**Comment by leng-yue** [comment]
> python -m cli to_wav -h
> 
> ----> Error: No such command 'to_wav'.
> 
> 
> 
> python -m cli length -h
> 
> 没问题
> 
> 
> 
> 没看出来是什么导致的不同

试试 to-wav?
