### ISSUE TITLE
Ubuntu 中多进程默认使用了 fork 的启动方法报错

### ISSUE THREAD

**Issue by seele-vollerei-ai** [fishaudio/audio-preprocess#14]
系统： Ubuntu 22.04.3 LTS
跑` fap transcribe` 命令的时候报错 - RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method
ProcessPoolExecutor 传入` mp_context=mp.get_context('spawn') `就可以使用了
或许可以加一下参数来指定这个？

**Comment by leng-yue** [comment]
加上了
